### PR TITLE
Only set project data if it does not exist

### PR DESCRIPTION
**Pull request by Yoplitein**
This fixes the (really ?%!#$%! annoying) behaviour of overwriting project data upon joining a workspace.

### CODE REVIEW

**Comment by ggreer** [comment]
The condition in your `if` statement will never be true, as even an empty window has a `folders` attribute on `project_data`.

I don't want to sound dismissive, but is your computer really slow or something? That's the only way an existing window's project data could be overwritten. If you look at the surrounding code, you'll see the steps are:

1. Try to find find an existing window with the workspace directory already open.
2. If that fails, try to find an existing window that is empty (no project data).
3. If that fails, open a new window.
4. Wait up to 500ms for the new window to open. (Sublime Text has no API that lets a plugin know when the `new_window` command completes.)
5. If after 500ms, no empty window can be found, just use the active window.

I'll change this code so that it inserts the path instead of stomping over all project data. That should give you the desired behavior. Sorry for the frustration caused.

**Comment by Yoplitein** [comment]
Empty windows do in fact have no project data, at least under ST3 on Windows.

Project data is only overwritten when joining an existing workspace, with the workspace's project open. Otherwise it opens a new window and creates a new project in memory.

**Comment by ggreer** [comment]
OK, master should be fixed. I'm going to test this a little more before tagging a release. Please let me know if that fixes your problem.

**Comment by Yoplitein** [comment]
Yep, that fixes it. Thanks!

**Comment by ggreer** [comment]
OK. I've tagged a new release: 3.5.2. Thanks for reporting this.

**Comment by Yoplitein** [comment]
#214 could also probably be closed now.

**Pull request closed without merging**
