### PR TITLE
Refresh the intermediate and CA certs

### PR DESCRIPTION
**Pull request by zedtux**
It was impossible for me to login and use Floobits in Sublime since I was facing an SSL certificate validation.

With this change, the plugin works well.

### CODE REVIEW

**Review by lastthyme — APPROVED** [review]

**Comment by Plutonium-239** [comment]
@ggreer @kans merge the pull request this has been happening to me as well

**Comment by zedtux** [comment]
@Plutonium-239 they're using a "Let's Encrypt" certificate, so each 90 days the certificate need to be renewed and therefore updated in this `cert.py` file.

An automated pipeline could solve this by submitting a PR to update the cert like 10/15 days before the expiration date.

All you have to do is to download the certificate from floobits.com and update the `cert.py` file.

**Comment by Plutonium-239** [comment]
@zedtux yeah, but someone would need to accept those PRs too :(

**Comment by zedtux** [comment]
For sure!

**Comment by plutonium-239** [comment]
@zedtux has the updated version been working for you? It still gives me an SSL error, `unable to get issuer certificate`. I confirmed with a friend that it's not just my system.

**Comment by plutonium-239** [comment]
@zedtux well i tried a lof things involving adding CA certs downloaded from the website (which were same as the ones in cert.py and floobits.pem) to my cacert.pem in hopes that maybe it is using just `certifi`'s store; However, none of it worked.
Really confused rn, and also worried about the future of floobits in general. Do you think if the host is "switched" to someone more involved in this (like yourself) it would be better? [or could just maintain the one you've forked and request the owners to link it as a community maintained thing]
I would also like to contribute wherever I can :)

**Comment by zedtux** [comment]
Regarding your [previous comment](https://github.com/Floobits/floobits-sublime/pull/249#issuecomment-949955091), this PR was working fine until the expiration date of the cert.
I haven't updated it recently so even do it has been merged, the issue remain since it needs first to be updated.

Now regarding your last comment, that's strange you didn't succeeded to make it working as updating the certs should work as it did work for me in the past.

> worried about the future of floobits in general

Well, this repos is *just* the Sublime Text plugin, not floobits itself, so until you have a big picture of floobits and have information I don't have, I don't see why the floobits project would be in danger due to this issue.

Anyways, what would help a lot would be to have a really SSL cert, so that it doesn't change (But it will depend on the revenue of the app), or to automate it.

I'm sorry but:
- I don't have the time to maintain this
- I'm not using it anymore

**Pull request merged**
